
name: Historico Sell In

on:
  # Continua a permitir execução manual
  workflow_dispatch:

  # Agendamentos (GitHub Actions usa UTC)
  schedule:
    # Inverno em PT (Nov–Mar): 03:10 UTC = 03:05 PT
    - cron: '5 3 * 11-12 *'  # Novembro–Dezembro
    - cron: '5 3 * 1-3 *'    # Janeiro–Março
    # Verão em PT (Apr–Oct): 02:10 UTC = 03:05 PT
    - cron: '5 2 * 4-10 *'   # Abril–Outubro

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar teste de conexão
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SITE_HOSTNAME: ${{ secrets.SITE_HOSTNAME }}
          SITE_PATH: ${{ secrets.SITE_PATH }}
        run: python Historico_Sell_In.py
        
      - name: Executar PhrOrd.py
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SITE_HOSTNAME: ${{ secrets.SITE_HOSTNAME }}
          SITE_PATH: ${{ secrets.SITE_PATH }}
        run: python PhrOrd.py
